#import <MapKit/MapKit.h>
#import <CoreLocation/CoreLocation.h>

FOUNDATION_EXPORT const double MITMapRegionDefaultPadding;
FOUNDATION_EXPORT const CLLocationDistance MITMapRegionDefaultMinimumRegionSize;
FOUNDATION_EXTERN const MKCoordinateRegion MKCoordinateRegionInvalid;

FOUNDATION_EXTERN BOOL MKCoordinateRegionIsValid(MKCoordinateRegion);
FOUNDATION_EXTERN MKCoordinateRegion MKCoordinateRegionForCoordinates(NSSet *coordinateValues);
FOUNDATION_EXTERN MKCoordinateRegion MKCoordinateRegionForCoordinatesWithPadding(NSSet *coordinateValues,CGFloat padding,CLLocationDistance minimumRegionSize);