#import "DiningMeal.h"
#import "DiningDay.h"
#import "DiningMealItem.h"
#import "CoreDataManager.h"

@implementation DiningMeal

@dynamic name;
@dynamic startTime;
@dynamic endTime;
@dynamic message;
@dynamic day;
@dynamic items;

+ (DiningMeal *)newMealWithDictionary:(NSDictionary* )dict {
    DiningMeal *meal = [CoreDataManager insertNewObjectForEntityForName:@"DiningMeal"];
    
    if (dict[@"name"]) {
        meal.name = dict[@"name"];
    }
    
    if (dict[@"message"]) {
        meal.message = dict[@"message"];
    }

    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:@"HH:mm"];
    [formatter setTimeZone:[NSTimeZone timeZoneWithName:@"America/New_York"]];

    if (dict[@"start_time"]) {
        NSDate *date = [formatter dateFromString:dict[@"start_time"]];
        meal.startTime = date;
    }

    if (dict[@"end_time"]) {
        NSDate *date = [formatter dateFromString:dict[@"end_time"]];
        meal.endTime = date;
    }
    
    for (NSDictionary *item in dict[@"items"]) {
        [meal addItemsObject:[DiningMealItem newItemWithDictionary:item]];
    }

    return meal;
}

// There appears to be a bug in Apple's autogenerated NSOrderedSet accessors: http://stackoverflow.com/questions/7385439/exception-thrown-in-nsorderedset-generated-accessors
- (void)addItemsObject:(DiningMeal *)value {
    NSMutableOrderedSet* tempSet = [NSMutableOrderedSet orderedSetWithOrderedSet:self.items];
    [tempSet addObject:value];
    self.items = tempSet;
}

- (NSString *)hoursSummary {
    
    if (!self.startTime || !self.endTime) {
        return nil;
    }
    
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setTimeZone:[NSTimeZone timeZoneWithName:@"America/New_York"]];
    [formatter setDateFormat:@"h"];
    
    NSString *startString = [formatter stringFromDate:self.startTime];
    NSString *endString = [formatter stringFromDate:self.endTime];
    
    [formatter setDateFormat:@":m"];
    
    NSString *startMinutes = [formatter stringFromDate:self.startTime];
    NSString *endMinutes = [formatter stringFromDate:self.endTime];
    
    if (![startMinutes isEqualToString:@":0"]) {
        startString = [startString stringByAppendingString:startMinutes];
    }
    if (![endMinutes isEqualToString:@":0"]) {
        endString = [endString stringByAppendingString:endMinutes];
    }
    
    [formatter setDateFormat:@"a"];
    
    startString = [startString stringByAppendingString:[formatter stringFromDate:self.startTime]];
    endString = [endString stringByAppendingString:[formatter stringFromDate:self.endTime]];
    
    return [[NSString stringWithFormat:@"%@ - %@", startString, endString] lowercaseString];
}

@end
