#import "DiningDay.h"
#import "HouseVenue.h"
#import "DiningMeal.h"
#import "CoreDataManager.h"

@implementation DiningDay

@dynamic date;
@dynamic message;
@dynamic meals;
@dynamic houseVenue;

+ (DiningDay *)newDayWithDictionary:(NSDictionary *)dict {
    DiningDay *day = [CoreDataManager insertNewObjectForEntityForName:@"DiningDay"];
    
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:@"yyyy-MM-dd"];
    [formatter setTimeZone:[NSTimeZone timeZoneWithName:@"America/New_York"]];
    NSDate *date = [formatter dateFromString:dict[@"date"]];
    day.date = date;
    
    if (dict[@"message"]) {
        day.message = dict[@"message"];
    }
    
    for (NSDictionary *mealDict in dict[@"meals"]) {
        [day addMealsObject:[DiningMeal newMealWithDictionary:mealDict]];
    }
    
    return day;
}

// There appears to be a bug in Apple's autogenerated NSOrderedSet accessors: http://stackoverflow.com/questions/7385439/exception-thrown-in-nsorderedset-generated-accessors
- (void)addMealsObject:(DiningMeal *)value {
    NSMutableOrderedSet* tempSet = [NSMutableOrderedSet orderedSetWithOrderedSet:self.meals];
    [tempSet addObject:value];
    self.meals = tempSet;
}

- (NSDate *) dateForTodayFromTimeString:(NSString *)time
{
    NSCalendar *cal = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
    NSDateComponents *comp = [cal components:NSYearCalendarUnit|NSMonthCalendarUnit|NSDayCalendarUnit|NSHourCalendarUnit|NSMinuteCalendarUnit|NSTimeZoneCalendarUnit fromDate:[NSDate date]];
    
    NSArray *timeComponents = [time componentsSeparatedByString:@":"];
    comp.hour = [[timeComponents objectAtIndex:0] integerValue];
    comp.minute = [[timeComponents objectAtIndex:1] integerValue];
    
    return [cal dateFromComponents:comp];
}

@end
